### ISSUE TITLE
[BUG] Add Maya swap support

### ISSUE THREAD

**Issue by johnnyluo** [vultisig/vultisig-windows#443] opened 2024-10-29 10:02 UTC
**Describe the bug**
Currently , when I select CACAO -> RUNE , it happily report quote , but it doesn't allow it on verify screen

**Comment by CopsLikeDonuts** [comment] 2024-10-29 10:41
Thats because swap CACAO via MAYA protocol is a deposit transaction @johnnyluo

**Comment by p-lopez100** [comment] 2024-11-04 06:53
Duplicate of #439. Closing to avoid duplicates

**Closed by p-lopez100** 2024-11-04 06:53 UTC
Labels: feature
